apiVersion: v1
kind: Service
metadata:
  name: cpm-assets-service
  labels:
    app: cpm-assets
spec:
  ports:
  - port: 80
    targetPort: 80
    name: client
  selector:
    app: cpm-assets
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpm-assets-deployment
  labels:
    app: cpm-assets
spec:
  serviceName: cpm-assets-service-storage
  replicas: 1
  selector:
    matchLabels:
      app: cpm-assets
  template:
    metadata:
      labels:
	app: cpm-assets
    spec:
      containers:
      - name: cpm-assets
        image: praisindo.azurecr.io/cpm/assets
        ports:
	- containerPort: 80
        volumeMounts:
        - name: cpm-assets-storage
          mountPath: /var/www/html/storage/
        env:
        - name: APP_ENV
          value: local
        - name: APP_DEBUG
          value: true
        - name: APP_TIMEZONE
          value: UTC
  volumeClaimTemplates:
  - metadata:
      name: cpm-assets-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi