apiVersion: v1
kind: Service
metadata:
  name: cpm-web-service
  labels:
    app: cpm-web
spec:
  ports:
  - port: 80
    targetPort: 80
    name: client
  selector:
    app: cpm-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpm-web-deployment
  labels:
    app: cpm-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpm-web
  template:
    metadata:
      labels:
	app: cpm-web
    spec:
      containers:
      - name: cpm-web
        image: praisindo.azurecr.io/cpm/web
        ports:
	- containerPort: 80
        env:
	- name: APP_ENV
          value: local
        - name: APP_DEBUG
          value: true
        - name: APP_TIMEZONE
          value: UTC
        - name: API_LUMEN
          value: https://cpm-api.praisindo.com/api/ #nanti perlu diganti dengan cpm-api-service
        - name: API_ASSETS
          value: https://cpm-ext.praisindo.com/ #nanti perlu diganti dengan alamat public dari cpm-assets-service