apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-test-pv-0201
  labels: 
    pv: local-test-pv
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-test-storage
  local:
    path: /mnt/local-test-pv-01/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ren-kube-n0002
          
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-test-pv-0202
  labels: 
    pv: local-test-pv
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-test-storage
  local:
    path: /mnt/local-test-pv-02/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ren-kube-n0002
 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-test-pv-0301
  labels: 
    pv: local-test-pv
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-test-storage
  local:
    path: /mnt/local-test-pv-01/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ren-kube-n0003
          
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-test-pv-0302
  labels: 
    pv: local-test-pv
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-test-storage
  local:
    path: /mnt/local-test-pv-02/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ren-kube-n0003

---
